### PR TITLE
Allow transformers-0.7

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This PR enables building the project with ghc-9.6.1

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Not sure how to test this change in the CI, but morpheus-graphql-client build with ghc-9.6.1. The only issue was #824

**Comment by nalchevanidze** [comment]
@TristanCacqueray. thanks. let us merge this first i will take over the testing it with ghc-9.6.1

**Comment by nalchevanidze** [comment]
by the way. could you please update it from `config/stack.yaml`. and then you run the `npm run setup`

**Review by nalchevanidze — APPROVED** [review]

**Comment by TristanCacqueray** [comment]
Looking at the build depends, it seems like they are not all compatible with ghc-9.6 yet, for example relude still has `base < 4.18`. Note that I got it to work by relaxing the bounds using nix `jailbreak`.

**Pull request merged**
