### PR TITLE
WIP: Feature/subscription support

### PR DESCRIPTION
**Pull request by sordina**
Want to add support for subscriptions as per https://github.com/morpheusgraphql/morpheus-graphql/issues/276

### CODE REVIEW

**Comment by nalchevanidze** [comment]
it is a bug:

https://github.com/morpheusgraphql/morpheus-graphql/blob/cfeddadef5670d156b77fcacb2745eac31fdf4ac/src/Data/Morpheus/Execution/Client/Selection.hs#L92

there it should select operation dataType according to `operationType` 
`QUERY` | `MUTATION` | `SUBSCRIPTION` but for now it selects  every time 
dataType of  query

**Comment by nalchevanidze** [comment]
this problem is fixed hier #302

**Comment by nalchevanidze** [comment]
hi @sordina , is this still in development, is there something where i could help you?

**Comment by sordina** [comment]
Hi @nalchevanidze , I got pulled away over the Christmas period but am still very keen to continue. I might have another go at trying this from the latest version of master since some things have changed since I was working on it last and then let you know where I get stuck!

**Comment by nalchevanidze** [comment]
i think i will close this pr for now. since it is outdated

**Comment by sordina** [comment]
Thanks @nalchevanidze sorry I never got round to coming up with a solution for this!

**Comment by nalchevanidze** [comment]
no worries :)

**Pull request closed without merging**
