### PR TITLE
Feature/add Interface for Subscriptions (without functionality)

### PR DESCRIPTION
**Pull request by msvbg**
Initial work on #113. Largely just a copy/paste/replace job from mutation → subscription.

### CODE REVIEW

**Comment by nalchevanidze** [comment]
is it already finished? please set WIP status if it is not ready

**Comment by msvbg** [comment]
It's probably mostly finished. I've also started working on websocket transport for subscriptions, which may need some further changes. I've marked the PR as a draft in case I need to change more things.

**Comment by msvbg** [comment]
Actually, let's just merge this right away. It might take a while to get the websocket transport working, and this will probably not need many changes.

**Comment by nalchevanidze** [comment]
i sound good. let merge your pull request before #112, because I did some refactoring there.

you can merge it. i renamed it

**Pull request merged**
