### PR TITLE
Add Suffixes directive

### PR DESCRIPTION
**Pull request by eunmin**
Hi~! :)
I'm having a great time with morpheus-graphql. This time I wanted to rename a type, so I tried to use Prefixes, Rename, DropNamespaces, but there was nothing suitable, so I created the Suffixes directive. Please take a look and merge or comment. Thanks.

### CODE REVIEW

**Comment by nalchevanidze** [comment]
@eunmin thanks. looks great. 
should we hide it with `excludeFromSchema _ = True`, since there is no value including it to derived schema? 
in that case we can do same for `Prefix` directive.

```hs
instance GQLDirective Suffixes where
  excludeFromSchema _ = True
```

**Comment by nalchevanidze** [comment]
and i realized we don't check if name really contains prefix or suffix. could you please add that too on both?

**Comment by todd-kim** [comment]
Yes, I'll set the `excludeFromSchema` value to `True` to hide both Prefixes and Suffixes from the schema.

**Comment by todd-kim** [comment]
As you commented, I've done the work and committed it.

**Review by nalchevanidze — APPROVED** [review]

**Pull request merged**
