### PR TITLE
Client readme examples

### PR DESCRIPTION
**Pull request by sordina**
Would there be other kinds of specific examples you'd be looking for? The main question I have is how you'd like to fetch the schemas of real APIs if I'm going to use them for examples.

### CODE REVIEW

**Comment by nalchevanidze** [comment]
example fails with stack:resolver `lts-12.16` and   lts-11.10 https://app.circleci.com/jobs/github/morpheusgraphql/morpheus-graphql/1233

```
  /root/project/examples/src/Client/StarWarsClient.hs:31:21: error:
        Variable not in scope: defaultHttpConfig :: HttpConfig
       |
    31 | resolver b = runReq defaultHttpConfig $ do
```
i think setting min  bound  to  `req` will solve this

**Comment by nalchevanidze** [comment]
@sordina  i configured the stack so , it pipelines does not fail anymore. but still would be great if you set min bound for req: 
```
  -  req  >= 2.1.0
```

**Comment by nalchevanidze** [comment]
the we can merge it

**Comment by sordina** [comment]
I still get this error if I update the req bounds:

```
In the dependencies for examples-0.1.0:
    aeson-1.4.5.0 from stack configuration does not match >=1.4.6.0 && <=1.6  (latest matching version is 1.4.6.0)
needed since examples is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true' in /Users/lyndon/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps in /Users/lyndon/code/morpheus-graphql/stack.yaml:

- aeson-1.4.6.0@sha256:560575b008a23960403a128331f0e59594786b5cd19a35be0cd74b9a7257958e,6980

Plan construction failed.
```

Am I missing something?

**Comment by sordina** [comment]
Hmm it does work if I put `allow-newer: true` in `stack.yaml`.

**Comment by sordina** [comment]
However when I put `allow-newer: true` in `examples/stack.yaml` I get the following error:

lyndon@difference|~/code/morpheus-graphql on feature/client-help.hs!?

```
± stack build
WARNING: Ignoring examples's bounds on aeson (>=1.4.6.0 && <=1.6); using aeson-1.4.5.0.
Reason: allow-newer enabled.
```

**Pull request merged**
