### PR TITLE
feat: replace Type Options with GQL Directives

### LINKED ISSUE #570: Consider replace TypeOptions with Custom Directives

### PR DESCRIPTION
**Pull request by nalchevanidze**
new features:  
- directives: __DropNamespace__ , __InputTypeNamespace__
- __VisitType__ methods: __visitFieldNames__,  __visitEnumNames__

breaking changes:
 - __visitTypeName__ signature changed  from  _a -> Text -> Text_ to _a -> Bool -> Text -> Text_
 - DEPRECATED:  __typeOptions__ , __GQLTypeOptions__, __prefixInputs__, __dropNamespaceOptions__, __defaultTypeOptions__
 - TH may require importing __InputTypeNamespace__ and __Rename__ directive

fixes #570

### CODE REVIEW

**Comment by thomasjm** [comment]
Hi @nalchevanidze -- I'm having a little trouble understanding the deprecation of `typeOptions` and the new directive way of doing things. I see there are new directives like `Rename` and `DropNamespace`, but don't these represent a decrease in power compared to the old `GQLTypeOptions` like `fieldLabelModifier` and `constructorTagModifier`? 

The old functions were convenient because I could directly use my Aeson options with them, and I'm not sure how to migrate to the new system (or if it's even possible). Do you have any advice? Thanks!

**Comment by thomasjm** [comment]
Thanks, that helps. However, I'm having trouble with custom directives. I tried copying the code directly from the tutorial, and had the following problems:

First, it's weird that you seemingly have to import `Data.Morpheus.Types.Internal.AST` to get the `DirectiveLocation(..)` constructors. Shouldn't these be exported somewhere more common?

Second, as written in the tutorial is missing a boolean argument in `visitTypeName`: `visitTypeName RemovePrefix {prefix} = T.drop (T.length prefix)`.

Anyway, when I try to use the `typeDirective` I get this error:

```bash
    • No instance for (morpheus-graphql-server-0.25.0:Data.Morpheus.Server.Types.GQLType.DeriveArguments
                         TYPE RemovePrefix)
        arising from a use of ‘typeDirective’
    • In the expression: typeDirective (RemovePrefix "asdf")
      In an equation for ‘directives’:
          directives _ = typeDirective (RemovePrefix "asdf")
      In the instance declaration for ‘GQLType IsSandboxLoaderType’
   |
Compilation failed.
```

**Comment by nalchevanidze** [comment]
as workaround add `import Data.Morpheus ()` and will fix the problem.  in general is kind of tricky bug that requires rewriting a huge part of code, will fix later.

**Comment by thomasjm** [comment]
That fixed that problem! Still having issues unfortunately though :(

For one thing, when I generate the schema with the `RemovePrefix` example, it puts weird stuff in the actual schema: 

```graphql
directive @RemovePrefix(prefix: String!) on OBJECT | INPUT_OBJECT

enum FooType @RemovePrefix(prefix: "") {
  FooTypeNotFound
  FooTypeExpired
  FooTypeAllowed
}
```

When I use this with Apollo GraphQL, it gets confused: `GraphQLSchemaValidationError: Directive "@RemovePrefix" may not be used on ENUM.`. I'm hoping there's a way to do the `fieldLabelModifier` stuff I want to do without adding stuff to the printed schema.

Secondly, I tried making my own directive and it crashes in a pretty opaque way. This one uses `id` on everything:

```haskell
data ChangeConstructor = ChangeConstructor
  deriving (Generic, GQLType)
instance GQLDirective ChangeConstructor where
  type DIRECTIVE_LOCATIONS ChangeConstructor = '[ 'OBJECT, 'INPUT_OBJECT ]
instance VisitType ChangeConstructor where
  visitEnumNames ChangeConstructor = id
  visitTypeName ChangeConstructor _ = id
  visitTypeDescription _ = id
```

When I use this as a `typeDirective` and to `printSchema`, I get

```
GQLError {message = \"could not encode arguments!\", locations = Nothing, path = Nothing, errorType = Just Internal, extensions = Nothing} :| []
```

**Comment by nalchevanidze** [comment]
for first case you can use on `GQLDirective`

```hs
excludeFromSchema _ = True
```

for second one, it expects object but got and empty type `ChangeConstructor`.

**Comment by thomasjm** [comment]
I made it `data ChangeConstructor = ChangeConstructor ()` and it worked! This is very strange of course. Thanks for the help!

**Comment by jberryman** [comment]
It would be awesome to get a clear migration guide for this change

**Pull request merged**
